name: sample
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'running the shellscripts'
          run:
           bash samle.sh
