name: sample3

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: "Please enter the ip_address"
        type: string

jobs:
  setup-test:
    runs-on: ubuntu-latest
    environment: e2e
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
